export const START_INTRO_ANIMATION_TIMING = 2;
export const STAGGER_CHILDREN_TIMING = 0.5;
export const START_SYNOPSIS_ANIMATION_TIMING =
  START_INTRO_ANIMATION_TIMING + STAGGER_CHILDREN_TIMING * 3;
export const LOADING_STATE_ANIMATION_DELAY = 0.5;
export const LOADING_STATE_DURATION =
  START_INTRO_ANIMATION_TIMING - LOADING_STATE_ANIMATION_DELAY;
